/**
 * Mouse Agent - The Programmer
 *
 * "To deny our own impulses is to deny the very thing that makes us human." — Mouse
 *
 * Mouse is the code generator who creates contracts, configurations, and
 * scaffolding for The Construct architecture migrations.
 */

import {
  BaseAgent,
  AgentTask,
  VerificationContext,
  createDefaultAgentConfig,
} from './base-agent.js';
import {
  GeneratedContract,
  GeneratedConfig,
  GeneratedFile,
  GeneratedArtifacts,
  PromptAnalysis,
  PromptVariable,
  FullAnalysis,
  AIProvider,
  AgentConfig,
  VerificationResult,
} from '../../types/morpheus.js';

// ============================================================================
// TEMPLATE SYSTEM
// ============================================================================

/**
 * Template variable pattern: {{variableName}} or {{#each items}}...{{/each}}
 */
const TEMPLATE_VAR_PATTERN = /\{\{(\w+)\}\}/g;
const TEMPLATE_EACH_PATTERN = /\{\{#each\s+(\w+)\}\}([\s\S]*?)\{\{\/each\}\}/g;
const TEMPLATE_IF_PATTERN = /\{\{#if\s+(\w+)\}\}([\s\S]*?)\{\{\/if\}\}/g;
const TEMPLATE_UNLESS_PATTERN = /\{\{#unless\s+(\w+)\}\}([\s\S]*?)\{\{\/unless\}\}/g;

/**
 * Contract template for generated contracts
 */
const CONTRACT_TEMPLATE = `# Generated Contract: {{name}}
# Generated by Mouse - The Programmer
# Source: {{sourcePath}}

contract:
  id: {{id}}
  version: "1.0.0"
  type: {{type}}
  name: {{name}}

  metadata:
    created_at: "{{createdAt}}"
    created_by: morpheus/mouse
    priority: {{priority}}
    tags:
{{#each tags}}
      - {{this}}
{{/each}}

  requirements:
    description: |
      {{description}}

{{#if hasTools}}
    tools:
      must_use:
{{#each tools}}
        - tool: {{this.name}}
          reason: "{{this.reason}}"
{{/each}}
{{/if}}

  goals:
    description: |
      {{goalDescription}}
    objectives:
{{#each objectives}}
      - {{this}}
{{/each}}
    success_threshold: {{successThreshold}}

  limitations:
    forbidden_actions:
{{#each forbiddenActions}}
      - {{this}}
{{/each}}
    constraints:
{{#each constraints}}
      - {{this}}
{{/each}}

{{#if hasPrompts}}
  prompts:
    system: |
      {{systemPrompt}}

    user: |
      {{userPrompt}}
{{/if}}

  limits:
    time:
      max_duration_ms: {{maxDuration}}
    retries:
      max_attempts: {{maxRetries}}
`;

/**
 * Architect config template
 */
const ARCHITECT_CONFIG_TEMPLATE = `# The Architect Configuration
# Generated by Mouse - The Programmer
# Project: {{projectName}}

version: "1.0.0"
name: {{projectName}}

# Global configuration
global:
  defaultModel: {{defaultModel}}
  maxCostPerRequest: {{maxCost}}
  logLevel: {{logLevel}}

# Contract paths
contracts:
  paths:
{{#each contractPaths}}
    - {{this}}
{{/each}}

# Truth sources
truth:
  sources:
{{#each truthSources}}
    - {{this}}
{{/each}}

# Allowed models
models:
  allowed:
{{#each allowedModels}}
    - {{this}}
{{/each}}
  preferred: {{preferredModel}}
`;

/**
 * Keymaker config template
 */
const KEYMAKER_CONFIG_TEMPLATE = `# Keymaker Configuration
# Generated by Mouse - The Programmer
# Multi-provider AI gateway configuration

version: "1.0.0"

# Providers configuration
providers:
{{#each providers}}
  {{this.name}}:
    enabled: {{this.enabled}}
    models:
{{#each this.models}}
      - {{this}}
{{/each}}
{{#if this.apiKeyEnv}}
    apiKeyEnv: {{this.apiKeyEnv}}
{{/if}}

{{/each}}

# Routing configuration
routing:
  strategy: {{routingStrategy}}
  fallback: {{fallbackProvider}}

# Rate limiting
rateLimiting:
  enabled: {{rateLimitEnabled}}
  requestsPerMinute: {{requestsPerMinute}}
`;

/**
 * TypeScript type template
 */
const TYPES_TEMPLATE = `/**
 * Generated Types for {{contractName}}
 * Generated by Mouse - The Programmer
 */

import { z } from 'zod';

// ============================================================================
// INPUT SCHEMA
// ============================================================================

export const {{contractPascal}}InputSchema = z.object({
{{#each inputFields}}
  {{this.name}}: {{this.zodType}},
{{/each}}
});

export type {{contractPascal}}Input = z.infer<typeof {{contractPascal}}InputSchema>;

// ============================================================================
// OUTPUT SCHEMA
// ============================================================================

export const {{contractPascal}}OutputSchema = z.object({
{{#each outputFields}}
  {{this.name}}: {{this.zodType}},
{{/each}}
});

export type {{contractPascal}}Output = z.infer<typeof {{contractPascal}}OutputSchema>;

// ============================================================================
// CONTRACT EXECUTOR TYPE
// ============================================================================

export interface {{contractPascal}}Contract {
  execute(input: {{contractPascal}}Input): Promise<{{contractPascal}}Output>;
}
`;

// ============================================================================
// MOUSE AGENT CLASS
// ============================================================================

/**
 * Mouse Agent - The Programmer
 *
 * Generates contracts, configurations, and code for The Construct.
 */
export class Mouse extends BaseAgent {
  private templateCache: Map<string, string> = new Map();

  constructor(config: AgentConfig = createDefaultAgentConfig(['generate-contract', 'generate-config', 'generate-types'])) {
    super('mouse', config);
  }

  // --------------------------------------------------------------------------
  // TASK EXECUTION
  // --------------------------------------------------------------------------

  protected async executeTask<TInput, TOutput>(
    task: AgentTask<TInput, TOutput>
  ): Promise<TOutput> {
    const input = task.input as Record<string, unknown>;

    switch (task.type) {
      case 'generate':
        return this.handleGenerateTask(input) as TOutput;
      case 'transform':
        return this.handleTransformTask(input) as TOutput;
      default:
        throw new Error(`Unsupported task type: ${task.type}`);
    }
  }

  private async handleGenerateTask(input: Record<string, unknown>): Promise<unknown> {
    const generateType = input.generateType as string;

    switch (generateType) {
      case 'contract':
        return this.generateContract(input.prompt as PromptAnalysis);
      case 'contracts':
        return this.generateContracts(input.prompts as PromptAnalysis[]);
      case 'config':
        return this.generateConfig(
          input.configType as GeneratedConfig['type'],
          input.analysis as FullAnalysis
        );
      case 'types':
        return this.generateTypes(input.contract as GeneratedContract);
      case 'scaffolding':
        return this.generateScaffolding(input.analysis as FullAnalysis);
      default:
        throw new Error(`Unknown generate type: ${generateType}`);
    }
  }

  private async handleTransformTask(input: Record<string, unknown>): Promise<unknown> {
    const transformType = input.transformType as string;

    switch (transformType) {
      case 'template':
        return this.expandTemplate(
          input.template as string,
          input.variables as Record<string, unknown>
        );
      case 'code':
        return this.transformCode(
          input.code as string,
          input.transformations as CodeTransformation[]
        );
      default:
        throw new Error(`Unknown transform type: ${transformType}`);
    }
  }

  protected async performVerification(
    itemId: string,
    context: VerificationContext
  ): Promise<VerificationResult> {
    // Mouse can verify generation-related checklist items
    if (itemId.includes('generate') || itemId.includes('scaffold') || itemId.includes('config')) {
      return {
        verified: true,
        evidence: 'Generation capability verified',
        confidence: 0.9,
        method: 'automated',
      };
    }

    return {
      verified: false,
      evidence: '',
      confidence: 0,
      method: 'manual',
      details: 'Item requires manual verification',
    };
  }

  // --------------------------------------------------------------------------
  // CONTRACT GENERATION
  // --------------------------------------------------------------------------

  /**
   * Generate a contract from a prompt analysis
   */
  async generateContract(prompt: PromptAnalysis): Promise<GeneratedContract> {
    const id = this.generateContractId(prompt);
    const name = this.generateContractName(prompt);

    // Extract from structure
    const systemPrompt = prompt.structure.systemPromptContent;
    const userTemplate = prompt.structure.userPromptTemplate;

    // Analyze the prompt to determine contract properties
    const contractType = this.inferContractType(prompt);
    const objectives = this.extractObjectives(prompt);
    const constraints = this.extractConstraints(prompt);
    const warnings: string[] = [];

    // Check for potential issues
    if (!systemPrompt && !userTemplate) {
      warnings.push('No prompts detected - contract may be incomplete');
    }

    if (prompt.variables.length === 0) {
      warnings.push('No variables detected - prompt may be static');
    }

    // Build template variables
    const templateVars: Record<string, unknown> = {
      id,
      name,
      type: contractType,
      sourcePath: prompt.location.file,
      createdAt: new Date().toISOString().split('T')[0],
      priority: 'normal',
      tags: this.generateTags(prompt),
      description: this.generateDescription(prompt),
      hasTools: false, // Tools are analyzed separately via ToolAnalysis
      tools: [],
      goalDescription: `Execute the ${name} operation successfully`,
      objectives,
      successThreshold: 8,
      forbiddenActions: ['Modify files without confirmation', 'Execute destructive operations'],
      constraints,
      hasPrompts: Boolean(systemPrompt || userTemplate),
      systemPrompt: systemPrompt || 'You are a helpful AI assistant.',
      userPrompt: this.convertToTemplatePrompt(userTemplate, prompt.variables),
      maxDuration: 30000,
      maxRetries: 3,
    };

    const content = this.expandTemplate(CONTRACT_TEMPLATE, templateVars);

    // Calculate confidence based on prompt completeness
    const confidence = this.calculateConfidence(prompt);

    return {
      id,
      name,
      sourcePrompt: prompt,
      content,
      outputPath: `contracts/${id}.yaml`,
      confidence,
      warnings,
    };
  }

  /**
   * Generate multiple contracts from prompt analyses
   */
  async generateContracts(prompts: PromptAnalysis[]): Promise<GeneratedContract[]> {
    const contracts: GeneratedContract[] = [];

    for (const prompt of prompts) {
      const contract = await this.generateContract(prompt);
      contracts.push(contract);
    }

    return contracts;
  }

  /**
   * Generate a contract ID from prompt analysis
   */
  private generateContractId(prompt: PromptAnalysis): string {
    // Use prompt ID if meaningful
    if (prompt.id && prompt.id !== 'unknown') {
      return this.toKebabCase(prompt.id);
    }

    // Try to infer from file name
    const fileName = prompt.location.file.split('/').pop() || 'unknown';
    const baseName = fileName.replace(/\.(ts|js|tsx|jsx)$/, '');
    return this.toKebabCase(baseName);
  }

  /**
   * Generate a contract name from prompt analysis
   */
  private generateContractName(prompt: PromptAnalysis): string {
    // Use prompt ID or file name
    if (prompt.id && prompt.id !== 'unknown') {
      return this.toTitleCase(prompt.id);
    }

    const fileName = prompt.location.file.split('/').pop() || 'Generated';
    const baseName = fileName.replace(/\.(ts|js|tsx|jsx)$/, '');
    return this.toTitleCase(baseName);
  }

  /**
   * Infer contract type from prompt analysis
   */
  private inferContractType(prompt: PromptAnalysis): string {
    const systemPrompt = prompt.structure.systemPromptContent;
    const userTemplate = prompt.structure.userPromptTemplate;

    if (systemPrompt?.includes('chat') || userTemplate?.includes('conversation')) {
      return 'chat';
    }
    if (systemPrompt?.includes('embed') || userTemplate?.includes('vector')) {
      return 'embedding';
    }
    return 'completion';
  }

  /**
   * Extract objectives from prompt analysis
   */
  private extractObjectives(prompt: PromptAnalysis): string[] {
    const objectives: string[] = [];

    if (prompt.structure.hasSystemPrompt) {
      objectives.push('Follow system prompt guidelines');
    }

    if (prompt.variables.length > 0) {
      objectives.push(`Process ${prompt.variables.length} input variable(s)`);
    }

    if (prompt.complexity === 'complex') {
      objectives.push('Handle complex multi-step processing');
    }

    if (objectives.length === 0) {
      objectives.push('Complete the requested task');
    }

    return objectives;
  }

  /**
   * Extract constraints from prompt analysis
   */
  private extractConstraints(prompt: PromptAnalysis): string[] {
    const constraints: string[] = [];
    const systemPrompt = prompt.structure.systemPromptContent;

    // Look for constraints in system prompt
    if (systemPrompt) {
      const constraintPatterns = [
        /must\s+not\s+([^.]+)/gi,
        /never\s+([^.]+)/gi,
        /don't\s+([^.]+)/gi,
        /avoid\s+([^.]+)/gi,
      ];

      for (const pattern of constraintPatterns) {
        let match;
        while ((match = pattern.exec(systemPrompt)) !== null) {
          constraints.push(match[1]!.trim());
        }
      }
    }

    if (constraints.length === 0) {
      constraints.push('Follow standard safety guidelines');
      constraints.push('Validate inputs before processing');
    }

    return constraints;
  }

  /**
   * Generate tags for a contract
   */
  private generateTags(prompt: PromptAnalysis): string[] {
    const tags: string[] = ['generated', 'morpheus'];

    if (prompt.type === 'template') {
      tags.push('template');
    }

    if (prompt.complexity === 'complex') {
      tags.push('complex');
    }

    return tags;
  }

  /**
   * Generate description for a contract
   */
  private generateDescription(prompt: PromptAnalysis): string {
    return `Generated contract from ${prompt.type} prompt at ${prompt.location.file}`;
  }

  /**
   * Convert user template to Construct template format
   */
  private convertToTemplatePrompt(template: string | undefined, variables: PromptVariable[]): string {
    if (!template) {
      if (variables.length > 0) {
        return variables.map(v => `{{${v.name}}}`).join('\n');
      }
      return '{{input}}';
    }

    // Convert various template formats to Mustache-style
    let converted = template;

    // Python f-string style: {variable}
    converted = converted.replace(/\{(\w+)\}/g, '{{$1}}');

    // JavaScript template literal style: ${variable}
    converted = converted.replace(/\$\{(\w+)\}/g, '{{$1}}');

    return converted;
  }

  /**
   * Calculate confidence score for generated contract
   */
  private calculateConfidence(prompt: PromptAnalysis): number {
    let confidence = 0.5; // Base confidence

    if (prompt.structure.hasSystemPrompt) confidence += 0.15;
    if (prompt.structure.hasUserPrompt) confidence += 0.15;
    if (prompt.variables.length > 0) confidence += 0.1;
    if (prompt.type === 'template') confidence += 0.05;
    if (prompt.complexity !== 'complex') confidence += 0.05;

    return Math.min(confidence, 1.0);
  }

  // --------------------------------------------------------------------------
  // CONFIG GENERATION
  // --------------------------------------------------------------------------

  /**
   * Generate a configuration file
   */
  async generateConfig(
    configType: GeneratedConfig['type'],
    analysis: FullAnalysis
  ): Promise<GeneratedConfig> {
    switch (configType) {
      case 'architect':
        return this.generateArchitectConfig(analysis);
      case 'keymaker':
        return this.generateKeymakerConfig(analysis);
      case 'sentinels':
        return this.generateSentinelsConfig(analysis);
      case 'oracle':
        return this.generateOracleConfig(analysis);
      case 'smith':
        return this.generateSmithConfig(analysis);
      default:
        throw new Error(`Unknown config type: ${configType}`);
    }
  }

  /**
   * Generate Architect configuration
   */
  private generateArchitectConfig(analysis: FullAnalysis): GeneratedConfig {
    // Extract project name from root path
    const projectName = analysis.project.rootPath.split('/').pop() || 'my-project';

    const templateVars: Record<string, unknown> = {
      projectName,
      defaultModel: this.inferDefaultModel(analysis),
      maxCost: 1.0,
      logLevel: 'info',
      contractPaths: ['./contracts'],
      truthSources: ['./truth/project.yaml'],
      allowedModels: this.inferAllowedModels(analysis),
      preferredModel: this.inferDefaultModel(analysis),
    };

    const content = this.expandTemplate(ARCHITECT_CONFIG_TEMPLATE, templateVars);

    return {
      type: 'architect',
      content,
      outputPath: 'architect.yaml',
      description: 'The Architect configuration for source of truth',
    };
  }

  /**
   * Generate Keymaker configuration
   */
  private generateKeymakerConfig(analysis: FullAnalysis): GeneratedConfig {
    const providers = this.inferProviders(analysis);

    const templateVars: Record<string, unknown> = {
      providers: providers.map(p => ({
        name: p,
        enabled: true,
        models: this.getModelsForProvider(p),
        apiKeyEnv: this.getApiKeyEnvForProvider(p),
      })),
      routingStrategy: 'cost-optimized',
      fallbackProvider: providers[0] || 'openai',
      rateLimitEnabled: true,
      requestsPerMinute: 60,
    };

    const content = this.expandTemplate(KEYMAKER_CONFIG_TEMPLATE, templateVars);

    return {
      type: 'keymaker',
      content,
      outputPath: 'keymaker.yaml',
      description: 'Keymaker multi-provider configuration',
    };
  }

  /**
   * Generate Sentinels configuration
   */
  private generateSentinelsConfig(analysis: FullAnalysis): GeneratedConfig {
    const content = `# Sentinels Configuration
# Generated by Mouse - The Programmer

version: "1.0.0"

# Validation settings
validation:
  strictMode: true
  validateInputs: true
  validateOutputs: true

# Quality thresholds
quality:
  minScore: 7
  requireEvidence: true

# Forbidden patterns
forbidden:
  paths:
    - pattern: "**/.env"
      reason: "Prevent access to secrets"
    - pattern: "**/node_modules/**"
      reason: "Prevent access to dependencies"
  actions:
    - "rm -rf"
    - "delete database"
`;

    return {
      type: 'sentinels',
      content,
      outputPath: 'sentinels.yaml',
      description: 'Sentinels QA enforcement configuration',
    };
  }

  /**
   * Generate Oracle configuration
   */
  private generateOracleConfig(analysis: FullAnalysis): GeneratedConfig {
    const content = `# Oracle Configuration
# Generated by Mouse - The Programmer

version: "1.0.0"

# XP and leveling
xp:
  basePerContract: 10
  bonusForQuality: 5
  levelThresholds:
    - level: 1
      xp: 0
    - level: 2
      xp: 100
    - level: 3
      xp: 300
    - level: 4
      xp: 600
    - level: 5
      xp: 1000

# Judgment criteria
judgment:
  qualityWeight: 0.4
  efficiencyWeight: 0.3
  safetyWeight: 0.3
`;

    return {
      type: 'oracle',
      content,
      outputPath: 'oracle.yaml',
      description: 'Oracle judgment and XP configuration',
    };
  }

  /**
   * Generate Agent Smith configuration
   */
  private generateSmithConfig(analysis: FullAnalysis): GeneratedConfig {
    const content = `# Agent Smith Configuration
# Generated by Mouse - The Programmer

version: "1.0.0"

# Security settings
security:
  zeroTrust: true
  auditAll: true
  requireApproval:
    - destructive-actions
    - external-api-calls
    - file-modifications

# Team configuration
team:
  brown:
    enabled: true
    role: authentication
  jones:
    enabled: true
    role: audit
  johnson:
    enabled: true
    role: rate-limiting
  thompson:
    enabled: true
    role: threat-detection
  jackson:
    enabled: true
    role: encryption
`;

    return {
      type: 'smith',
      content,
      outputPath: 'smith.yaml',
      description: 'Agent Smith security configuration',
    };
  }

  // --------------------------------------------------------------------------
  // TYPE GENERATION
  // --------------------------------------------------------------------------

  /**
   * Generate TypeScript types for a contract
   */
  async generateTypes(contract: GeneratedContract): Promise<GeneratedFile> {
    const contractPascal = this.toPascalCase(contract.id);

    // Parse contract content to extract input/output fields
    const inputFields = this.extractContractFields(contract, 'input');
    const outputFields = this.extractContractFields(contract, 'output');

    const templateVars: Record<string, unknown> = {
      contractName: contract.name,
      contractPascal,
      inputFields,
      outputFields,
    };

    const content = this.expandTemplate(TYPES_TEMPLATE, templateVars);

    return {
      path: `src/contracts/${contract.id}.types.ts`,
      content,
      type: 'source',
      description: `TypeScript types for ${contract.name}`,
    };
  }

  /**
   * Extract fields from contract for type generation
   */
  private extractContractFields(
    contract: GeneratedContract,
    fieldType: 'input' | 'output'
  ): Array<{ name: string; zodType: string }> {
    const fields: Array<{ name: string; zodType: string }> = [];

    // If we have source prompt, use its variables
    if (contract.sourcePrompt && fieldType === 'input') {
      for (const variable of contract.sourcePrompt.variables) {
        fields.push({
          name: variable.name,
          zodType: this.inferZodType(variable.type || 'string'),
        });
      }
    }

    // Default fields if none found
    if (fields.length === 0) {
      if (fieldType === 'input') {
        fields.push({ name: 'input', zodType: 'z.string()' });
      } else {
        fields.push({ name: 'result', zodType: 'z.string()' });
      }
    }

    return fields;
  }

  /**
   * Infer Zod type from variable type
   */
  private inferZodType(type: string): string {
    switch (type.toLowerCase()) {
      case 'string':
        return 'z.string()';
      case 'number':
        return 'z.number()';
      case 'boolean':
        return 'z.boolean()';
      case 'array':
        return 'z.array(z.unknown())';
      case 'object':
        return 'z.record(z.unknown())';
      default:
        return 'z.string()';
    }
  }

  // --------------------------------------------------------------------------
  // SCAFFOLDING GENERATION
  // --------------------------------------------------------------------------

  /**
   * Generate project scaffolding for The Construct
   */
  async generateScaffolding(analysis: FullAnalysis): Promise<GeneratedArtifacts> {
    const contracts: GeneratedContract[] = [];
    const configs: GeneratedConfig[] = [];
    const scaffolding: GeneratedFile[] = [];

    // Generate configs
    configs.push(await this.generateArchitectConfig(analysis));
    configs.push(await this.generateKeymakerConfig(analysis));
    configs.push(this.generateSentinelsConfig(analysis));
    configs.push(this.generateOracleConfig(analysis));
    configs.push(this.generateSmithConfig(analysis));

    // Generate index file
    scaffolding.push({
      path: 'src/construct/index.ts',
      content: this.generateConstructIndex(),
      type: 'source',
      description: 'Main Construct exports',
    });

    // Generate contracts from prompts if available
    if (analysis.aiUsage?.prompts) {
      for (const prompt of analysis.aiUsage.prompts) {
        const contract = await this.generateContract(prompt);
        contracts.push(contract);
      }
    }

    return {
      contracts,
      configs,
      scaffolding,
    };
  }

  /**
   * Generate Construct index file
   */
  private generateConstructIndex(): string {
    return `/**
 * The Construct - AI Orchestration
 * Generated by Mouse - The Programmer
 */

// Re-export core components
export * from './architect.js';
export * from './oracle.js';
export * from './sentinels.js';
export * from './keymaker.js';
export * from './agents.js';

// Export types
export type * from './types.js';
`;
  }

  // --------------------------------------------------------------------------
  // TEMPLATE SYSTEM
  // --------------------------------------------------------------------------

  /**
   * Expand a template with variables
   */
  expandTemplate(template: string, variables: Record<string, unknown>): string {
    let result = template;

    // Process #each blocks
    result = result.replace(TEMPLATE_EACH_PATTERN, (_match, arrayName, content) => {
      const array = variables[arrayName];
      if (!Array.isArray(array)) return '';

      return array.map((item, index) => {
        let itemContent = content;
        if (typeof item === 'object' && item !== null) {
          // Replace {{this.property}} with item properties
          itemContent = itemContent.replace(/\{\{this\.(\w+)\}\}/g, (_: string, prop: string) => {
            return String((item as Record<string, unknown>)[prop] ?? '');
          });
        }
        // Replace {{this}} with the item itself
        itemContent = itemContent.replace(/\{\{this\}\}/g, String(item));
        // Replace {{@index}} with the index
        itemContent = itemContent.replace(/\{\{@index\}\}/g, String(index));
        return itemContent;
      }).join('');
    });

    // Process #if blocks
    result = result.replace(TEMPLATE_IF_PATTERN, (_match, varName, content) => {
      const value = variables[varName];
      return value ? content : '';
    });

    // Process #unless blocks
    result = result.replace(TEMPLATE_UNLESS_PATTERN, (_match, varName, content) => {
      const value = variables[varName];
      return !value ? content : '';
    });

    // Process simple variables
    result = result.replace(TEMPLATE_VAR_PATTERN, (_match, varName) => {
      const value = variables[varName];
      if (value === undefined || value === null) return '';
      return String(value);
    });

    return result;
  }

  /**
   * Register a custom template
   */
  registerTemplate(name: string, template: string): void {
    this.templateCache.set(name, template);
  }

  /**
   * Get a registered template
   */
  getTemplate(name: string): string | undefined {
    return this.templateCache.get(name);
  }

  /**
   * Clear template cache
   */
  clearTemplateCache(): void {
    this.templateCache.clear();
  }

  // --------------------------------------------------------------------------
  // CODE TRANSFORMATION
  // --------------------------------------------------------------------------

  /**
   * Transform code with specified transformations
   */
  private transformCode(code: string, transformations: CodeTransformation[]): string {
    let result = code;

    for (const transform of transformations) {
      switch (transform.type) {
        case 'replace':
          result = result.replace(
            new RegExp(transform.pattern!, 'g'),
            transform.replacement!
          );
          break;
        case 'prepend':
          result = transform.content! + '\n' + result;
          break;
        case 'append':
          result = result + '\n' + transform.content!;
          break;
        case 'wrap':
          result = transform.before! + result + transform.after!;
          break;
      }
    }

    return result;
  }

  // --------------------------------------------------------------------------
  // UTILITY METHODS
  // --------------------------------------------------------------------------

  /**
   * Infer default model from analysis
   */
  private inferDefaultModel(analysis: FullAnalysis): string {
    if (analysis.aiUsage && Array.isArray(analysis.aiUsage.providers)) {
      const providerNames = analysis.aiUsage.providers.map(p => p.provider);
      if (providerNames.includes('openai')) return 'gpt-4o-mini';
      if (providerNames.includes('anthropic')) return 'claude-3-haiku-20240307';
      if (providerNames.includes('google')) return 'gemini-1.5-flash';
    }
    return 'gpt-4o-mini';
  }

  /**
   * Infer allowed models from analysis
   */
  private inferAllowedModels(analysis: FullAnalysis): string[] {
    const models: string[] = [];

    if (analysis.aiUsage && Array.isArray(analysis.aiUsage.providers)) {
      const providerNames = analysis.aiUsage.providers.map(p => p.provider);
      if (providerNames.includes('openai')) {
        models.push('gpt-4o', 'gpt-4o-mini', 'gpt-4-turbo');
      }
      if (providerNames.includes('anthropic')) {
        models.push('claude-3-5-sonnet-20241022', 'claude-3-haiku-20240307');
      }
      if (providerNames.includes('google')) {
        models.push('gemini-1.5-pro', 'gemini-1.5-flash');
      }
    }

    if (models.length === 0) {
      models.push('gpt-4o-mini', 'claude-3-haiku-20240307');
    }

    return models;
  }

  /**
   * Infer providers from analysis
   */
  private inferProviders(analysis: FullAnalysis): AIProvider[] {
    if (analysis.aiUsage && Array.isArray(analysis.aiUsage.providers) && analysis.aiUsage.providers.length > 0) {
      return analysis.aiUsage.providers.map(p => p.provider);
    }
    return ['openai'];
  }

  /**
   * Get models for a provider
   */
  private getModelsForProvider(provider: AIProvider): string[] {
    switch (provider) {
      case 'openai':
        return ['gpt-4o', 'gpt-4o-mini', 'gpt-4-turbo'];
      case 'anthropic':
        return ['claude-3-5-sonnet-20241022', 'claude-3-haiku-20240307'];
      case 'google':
        return ['gemini-1.5-pro', 'gemini-1.5-flash'];
      case 'cohere':
        return ['command-r-plus', 'command-r'];
      case 'mistral':
        return ['mistral-large', 'mistral-medium'];
      default:
        return [];
    }
  }

  /**
   * Get API key environment variable for a provider
   */
  private getApiKeyEnvForProvider(provider: AIProvider): string {
    switch (provider) {
      case 'openai':
        return 'OPENAI_API_KEY';
      case 'anthropic':
        return 'ANTHROPIC_API_KEY';
      case 'google':
        return 'GOOGLE_API_KEY';
      case 'cohere':
        return 'COHERE_API_KEY';
      case 'mistral':
        return 'MISTRAL_API_KEY';
      case 'azure':
        return 'AZURE_OPENAI_API_KEY';
      default:
        return `${provider.toUpperCase()}_API_KEY`;
    }
  }

  /**
   * Convert string to kebab-case
   */
  private toKebabCase(str: string): string {
    return str
      .replace(/([a-z])([A-Z])/g, '$1-$2')
      .replace(/[\s_]+/g, '-')
      .toLowerCase();
  }

  /**
   * Convert string to PascalCase
   */
  private toPascalCase(str: string): string {
    return str
      .split(/[-_\s]+/)
      .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
      .join('');
  }

  /**
   * Convert string to Title Case
   */
  private toTitleCase(str: string): string {
    return str
      .split(/[-_\s]+/)
      .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
      .join(' ');
  }
}

// ============================================================================
// TYPES
// ============================================================================

/**
 * Code transformation definition
 */
interface CodeTransformation {
  type: 'replace' | 'prepend' | 'append' | 'wrap';
  pattern?: string;
  replacement?: string;
  content?: string;
  before?: string;
  after?: string;
}

// ============================================================================
// FACTORY FUNCTION
// ============================================================================

/**
 * Create a Mouse agent instance
 *
 * "To deny our own impulses is to deny the very thing that makes us human."
 */
export function createMouse(config?: AgentConfig): Mouse {
  return new Mouse(config);
}
