/**
 * Stylist Agent — Generates CSS stylesheets
 *
 * Uses the generate-styles contract to produce modern, responsive CSS.
 * In mock mode, returns a realistic placeholder stylesheet.
 */

import type { Contract, AgentSubmission } from '../../../src/index.js';
import type { Sentinels } from '../../../src/index.js';
import { createWorker, isMockMode } from '../config.js';

export interface StyleSpec {
  primaryColor: string;
  secondaryColor: string;
  fontFamily: string;
  darkMode: boolean;
}

export interface StylistResult {
  css: string;
  submission: AgentSubmission;
}

/**
 * Run the stylist agent to generate a CSS stylesheet.
 */
export async function runStylist(
  spec: StyleSpec,
  contract: Contract,
  sentinels: Sentinels,
): Promise<StylistResult> {
  const worker = createWorker(sentinels);

  const task = {
    id: `style-${Date.now()}`,
    type: 'generation',
    description: 'Generate a responsive CSS stylesheet',
    inputs: {
      primaryColor: spec.primaryColor,
      secondaryColor: spec.secondaryColor,
      fontFamily: spec.fontFamily,
      darkMode: spec.darkMode,
    },
    expectedOutput: 'A complete CSS3 stylesheet with custom properties',
    systemPrompt: [
      'You are a CSS expert specializing in modern, responsive design.',
      'Generate a complete stylesheet with:',
      '- CSS custom properties for all colors',
      '- Mobile-first responsive breakpoints',
      '- Flexbox/Grid layouts',
      '- No !important declarations',
      `Primary color: ${spec.primaryColor}`,
      `Secondary color: ${spec.secondaryColor}`,
      `Font: ${spec.fontFamily}`,
    ].join('\n'),
  };

  const startTime = Date.now();
  const result = await worker.execute(task, contract);
  const duration = Date.now() - startTime;

  const css = !isMockMode() && typeof result.output === 'string'
    ? result.output
    : generateMockCss(spec);

  return {
    css,
    submission: {
      agentId: 'agent-stylist',
      contractId: contract.contract.id,
      output: css,
      duration,
      cost: result.cost,
      retries: 0,
      toolsUsed: ['css_generator'],
    },
  };
}

function generateMockCss(spec: StyleSpec): string {
  return `/* Generated by The Construct — Stylist Agent */

:root {
  --color-primary: ${spec.primaryColor};
  --color-secondary: ${spec.secondaryColor};
  --color-text: #1a1a2e;
  --color-bg: #ffffff;
  --color-surface: #f5f5f5;
  --font-family: ${spec.fontFamily};
  --font-size-base: 1rem;
  --spacing-unit: 0.5rem;
  --max-width: 1200px;
  --border-radius: 8px;
}

${spec.darkMode ? `@media (prefers-color-scheme: dark) {
  :root {
    --color-text: #e0e0e0;
    --color-bg: #1a1a2e;
    --color-surface: #2d2d44;
  }
}` : ''}

/* Reset */
*,
*::before,
*::after {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

/* Base */
body {
  font-family: var(--font-family);
  font-size: var(--font-size-base);
  color: var(--color-text);
  background-color: var(--color-bg);
  line-height: 1.6;
}

/* Layout */
header {
  background-color: var(--color-primary);
  color: white;
  padding: calc(var(--spacing-unit) * 3);
}

nav ul {
  display: flex;
  gap: calc(var(--spacing-unit) * 3);
  list-style: none;
  max-width: var(--max-width);
  margin: 0 auto;
}

nav a {
  color: white;
  text-decoration: none;
  font-weight: 500;
}

nav a:hover {
  text-decoration: underline;
}

main {
  max-width: var(--max-width);
  margin: 0 auto;
  padding: calc(var(--spacing-unit) * 4);
}

h1 {
  font-size: 2.5rem;
  margin-bottom: calc(var(--spacing-unit) * 4);
  color: var(--color-primary);
}

h2 {
  font-size: 1.75rem;
  margin-bottom: calc(var(--spacing-unit) * 2);
  color: var(--color-secondary);
}

section {
  margin-bottom: calc(var(--spacing-unit) * 6);
  padding: calc(var(--spacing-unit) * 4);
  background-color: var(--color-surface);
  border-radius: var(--border-radius);
}

footer {
  background-color: var(--color-surface);
  padding: calc(var(--spacing-unit) * 4);
  text-align: center;
  margin-top: calc(var(--spacing-unit) * 8);
}

/* Responsive */
@media (max-width: 768px) {
  nav ul {
    flex-direction: column;
    gap: var(--spacing-unit);
  }

  h1 {
    font-size: 1.75rem;
  }

  main {
    padding: calc(var(--spacing-unit) * 2);
  }
}`;
}
